baseURL = 'https://vnykmshr.github.io/goflow/'
languageCode = 'en-us'
title = 'goflow'
theme = 'hugo-book'

# Book theme parameters
[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/vnykmshr/goflow'
  BookEditPath = 'edit/main/docs/content'
  BookSection = 'docs'
  # Show breadcrumbs for navigation context
  BookBreadcrumb = true
  # Logo/brand (relative to static/, Hugo's relURL handles baseURL)
  BookLogo = 'goflow-logo.svg'

# Code highlighting - use noClasses for theme-aware highlighting
[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

# Menu links shown in header
[menu]
  [[menu.before]]
    name = "GitHub"
    url = "https://github.com/vnykmshr/goflow"
    weight = 10
  [[menu.before]]
    name = "API Docs"
    url = "https://pkg.go.dev/github.com/vnykmshr/goflow"
    weight = 20

  # After menu (shown after sidebar content)
  [[menu.after]]
    name = "Examples"
    url = "https://github.com/vnykmshr/goflow/tree/main/examples"
    weight = 10
